<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Init7Tv.Dal\Init7Tv.Dal.csproj" />
      <ProjectReference Include="..\Init7Tv.Dto\Init7Tv.Dto.csproj" />
      <ProjectReference Include="..\Init7Tv.Shared\Init7Tv.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MailKit" Version="4.14.1" />
      <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.2" />
    </ItemGroup>

</Project>
