<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Init7Tv.Shared\Init7Tv.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="bin\Debug\net10.0\BuildHost-net472\cs\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-net472\de\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-net472\es\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-net472\fr\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-net472\it\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-net472\ja\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-net472\ko\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-net472\pl\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-net472\pt-BR\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-net472\ru\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-net472\tr\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-net472\zh-Hans\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-net472\zh-Hant\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-netcore\cs\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-netcore\de\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-netcore\es\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-netcore\fr\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-netcore\it\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-netcore\ja\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-netcore\ko\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-netcore\pl\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-netcore\pt-BR\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-netcore\ru\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-netcore\tr\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-netcore\zh-Hans\" />
      <Folder Include="bin\Debug\net10.0\BuildHost-netcore\zh-Hant\" />
    </ItemGroup>

</Project>
